[package]
name = "smash"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.23.2"
tracing = "0.1"
tracing-subscriber = "0.3"
dirs = "1"
pest = "2.4"
pest_derive = "2.4"
signal-hook = "0.2"
libc = "0"
nix = "0"
anyhow = "1.0"
thiserror = "1.0"
